/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as PillarsRouteImport } from './routes/pillars'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinCellRouteImport } from './routes/join-cell'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'

const ServicesRoute = ServicesRouteImport.update({
            id: '/services',path: '/services',getParentRoute: () => rootRouteImport
          }as any)
const SermonsRoute = SermonsRouteImport.update({
            id: '/sermons',path: '/sermons',getParentRoute: () => rootRouteImport
          }as any)
const PillarsRoute = PillarsRouteImport.update({
            id: '/pillars',path: '/pillars',getParentRoute: () => rootRouteImport
          }as any)
const LoginRoute = LoginRouteImport.update({
            id: '/login',path: '/login',getParentRoute: () => rootRouteImport
          }as any)
const JoinCellRoute = JoinCellRouteImport.update({
            id: '/join-cell',path: '/join-cell',getParentRoute: () => rootRouteImport
          }as any)
const EventsRoute = EventsRouteImport.update({
            id: '/events',path: '/events',getParentRoute: () => rootRouteImport
          }as any)
const DashboardRoute = DashboardRouteImport.update({
            id: '/dashboard',path: '/dashboard',getParentRoute: () => rootRouteImport
          }as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
            id: '/dashboard/',path: '/',getParentRoute: () => DashboardRoute
          }as any)
const ContactRoute = ContactRouteImport.update({
            id: '/contact',path: '/contact',getParentRoute: () => rootRouteImport
          }as any)
const BranchesRoute = BranchesRouteImport.update({
            id: '/branches',path: '/branches',getParentRoute: () => rootRouteImport
          }as any)
const BooksRoute = BooksRouteImport.update({
            id: '/books',path: '/books',getParentRoute: () => rootRouteImport
          }as any)
const AboutRoute = AboutRouteImport.update({
            id: '/about',path: '/about',getParentRoute: () => rootRouteImport
          }as any)
const IndexRoute = IndexRouteImport.update({
            id: '/',path: '/',getParentRoute: () => rootRouteImport
          }as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
            id: '/$bookId',path: '/$bookId',getParentRoute: () => BooksRoute
          }as any)

export interface FileRoutesByFullPath {
'/': typeof IndexRoute,'/about': typeof AboutRoute,'/books': typeof BooksRouteWithChildren,'/branches': typeof BranchesRoute,'/contact': typeof ContactRoute,'/dashboard': typeof DashboardRouteWithChildren,'/events': typeof EventsRoute,'/join-cell': typeof JoinCellRoute,'/login': typeof LoginRoute,'/pillars': typeof PillarsRoute,'/sermons': typeof SermonsRoute,'/services': typeof ServicesRoute,'/books/$bookId': typeof BooksBookIdRoute
}
export interface FileRoutesByTo {
'/': typeof IndexRoute,'/about': typeof AboutRoute,'/books': typeof BooksRouteWithChildren,'/branches': typeof BranchesRoute,'/contact': typeof ContactRoute,'/dashboard': typeof DashboardRouteWithChildren,'/events': typeof EventsRoute,'/join-cell': typeof JoinCellRoute,'/login': typeof LoginRoute,'/pillars': typeof PillarsRoute,'/sermons': typeof SermonsRoute,'/services': typeof ServicesRoute,'/books/$bookId': typeof BooksBookIdRoute
}
export interface FileRoutesById {
'__root__': typeof rootRouteImport,
'/': typeof IndexRoute,'/about': typeof AboutRoute,'/books': typeof BooksRouteWithChildren,'/branches': typeof BranchesRoute,'/contact': typeof ContactRoute,'/dashboard': typeof DashboardRouteWithChildren,'/dashboard/': typeof DashboardIndexRoute,'/events': typeof EventsRoute,'/join-cell': typeof JoinCellRoute,'/login': typeof LoginRoute,'/pillars': typeof PillarsRoute,'/sermons': typeof SermonsRoute,'/services': typeof ServicesRoute,'/books/$bookId': typeof BooksBookIdRoute
}
export interface FileRouteTypes {
fileRoutesByFullPath: FileRoutesByFullPath
fullPaths: '/'|'/about'|'/books'|'/branches'|'/contact'|'/dashboard'|'/events'|'/join-cell'|'/login'|'/pillars'|'/sermons'|'/services'|'/books/$bookId'
fileRoutesByTo: FileRoutesByTo
to: '/'|'/about'|'/books'|'/branches'|'/contact'|'/dashboard'|'/events'|'/join-cell'|'/login'|'/pillars'|'/sermons'|'/services'|'/books/$bookId'
id: '__root__'|'/'|'/about'|'/books'|'/branches'|'/contact'|'/dashboard'|'/dashboard/'|'/events'|'/join-cell'|'/login'|'/pillars'|'/sermons'|'/services'|'/books/$bookId'
fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
IndexRoute: typeof IndexRoute,AboutRoute: typeof AboutRoute,BooksRoute: typeof BooksRouteWithChildren,BranchesRoute: typeof BranchesRoute,ContactRoute: typeof ContactRoute,DashboardRoute: typeof DashboardRouteWithChildren,EventsRoute: typeof EventsRoute,JoinCellRoute: typeof JoinCellRoute,LoginRoute: typeof LoginRoute,PillarsRoute: typeof PillarsRoute,SermonsRoute: typeof SermonsRoute,ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
          id: '/services'
          path: '/services'
          fullPath: '/services'
          preLoaderRoute: typeof ServicesRouteImport
          parentRoute: typeof rootRouteImport
        }
'/sermons': {
          id: '/sermons'
          path: '/sermons'
          fullPath: '/sermons'
          preLoaderRoute: typeof SermonsRouteImport
          parentRoute: typeof rootRouteImport
        }
'/pillars': {
          id: '/pillars'
          path: '/pillars'
          fullPath: '/pillars'
          preLoaderRoute: typeof PillarsRouteImport
          parentRoute: typeof rootRouteImport
        }
'/login': {
          id: '/login'
          path: '/login'
          fullPath: '/login'
          preLoaderRoute: typeof LoginRouteImport
          parentRoute: typeof rootRouteImport
        }
'/join-cell': {
          id: '/join-cell'
          path: '/join-cell'
          fullPath: '/join-cell'
          preLoaderRoute: typeof JoinCellRouteImport
          parentRoute: typeof rootRouteImport
        }
'/events': {
          id: '/events'
          path: '/events'
          fullPath: '/events'
          preLoaderRoute: typeof EventsRouteImport
          parentRoute: typeof rootRouteImport
        }
'/dashboard': {
          id: '/dashboard'
          path: '/dashboard'
          fullPath: '/dashboard'
          preLoaderRoute: typeof DashboardRouteImport
          parentRoute: typeof rootRouteImport
        }
'/dashboard/': {
          id: '/dashboard/'
          path: '/'
          fullPath: '/dashboard'
          preLoaderRoute: typeof DashboardIndexRouteImport
          parentRoute: typeof DashboardRoute
        }
'/contact': {
          id: '/contact'
          path: '/contact'
          fullPath: '/contact'
          preLoaderRoute: typeof ContactRouteImport
          parentRoute: typeof rootRouteImport
        }
'/branches': {
          id: '/branches'
          path: '/branches'
          fullPath: '/branches'
          preLoaderRoute: typeof BranchesRouteImport
          parentRoute: typeof rootRouteImport
        }
'/books': {
          id: '/books'
          path: '/books'
          fullPath: '/books'
          preLoaderRoute: typeof BooksRouteImport
          parentRoute: typeof rootRouteImport
        }
'/about': {
          id: '/about'
          path: '/about'
          fullPath: '/about'
          preLoaderRoute: typeof AboutRouteImport
          parentRoute: typeof rootRouteImport
        }
'/': {
          id: '/'
          path: '/'
          fullPath: '/'
          preLoaderRoute: typeof IndexRouteImport
          parentRoute: typeof rootRouteImport
        }
'/books/$bookId': {
          id: '/books/$bookId'
          path: '/$bookId'
          fullPath: '/books/$bookId'
          preLoaderRoute: typeof BooksBookIdRouteImport
          parentRoute: typeof BooksRoute
        }
  }
}



interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(DashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,AboutRoute: AboutRoute,BooksRoute: BooksRouteWithChildren,BranchesRoute: BranchesRoute,ContactRoute: ContactRoute,DashboardRoute: DashboardRouteWithChildren,EventsRoute: EventsRoute,JoinCellRoute: JoinCellRoute,LoginRoute: LoginRoute,PillarsRoute: PillarsRoute,SermonsRoute: SermonsRoute,ServicesRoute: ServicesRoute
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}